version: "3.9"

services:

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: mydb
    depends_on:
      - db
    restart: always
    networks:
      macvlan_net:
        ipv4_address: 192.168.200.10

  db:
    build: ./database
    container_name: postgresdb
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      macvlan_net:
        ipv4_address: 192.168.200.11

volumes:
  pgdata:

networks:
  macvlan_net:
    external: true